
const fs = require('fs');
const fetch = (...args) => import('node-fetch').then(({ default: fetch }) => fetch(...args));

async function fetchMajorCities() {
    const query = `
        [out:json][timeout:300];
        area["ISO3166-1"="DE"]->.searchArea;
        (
          node["place"~"city|town"](area.searchArea);
          relation["place"~"city|town"](area.searchArea);
        );
        out tags center;
    `;

    console.log("Fetching from Overpass...");
    try {
        const response = await fetch("https://overpass-api.de/api/interpreter", {
            method: "POST",
            body: "data=" + encodeURIComponent(query)
        });

        if (!response.ok) throw new Error(response.statusText);

        const data = await response.json();
        console.log(`Received ${data.elements.length} elements.`);

        let cities = data.elements.map(el => {
            const tags = el.tags || {};
            const population = parseInt((tags.population || "0").replace(/\D/g, ''));
            const lat = el.lat || el.center?.lat;
            const lon = el.lon || el.center?.lon;

            return {
                id: el.id,
                name: tags.name,
                nameRu: tags["name:ru"],
                population: population,
                lat: lat,
                lon: lon,
                tags: tags
            };
        })
            .filter(c => c.population > 20000 && c.lat && c.lon && c.name);

        cities.sort((a, b) => b.population - a.population);

        const uniqueCities = [];
        const seen = new Set();
        for (const city of cities) {
            const key = city.name.toLowerCase();
            if (!seen.has(key)) {
                seen.add(key);
                uniqueCities.push(city);
            }
        }
        cities = uniqueCities;

        console.log(`Retained ${cities.length} unique cities > 20k.`);

        let content = `// Generated by scripts/generate_cities.js\n`;
        content += `export const GERMAN_CITIES = [\n`;

        cities.forEach((city, index) => {
            const name = city.name.toLowerCase();
            const simpleName = name.replace(/ü/g, 'u').replace(/ö/g, 'o').replace(/ä/g, 'a').replace(/ß/g, 'ss');

            let triggers = [name[0], name.substring(0, 2)];
            if (city.nameRu) {
                const nameRu = city.nameRu.toLowerCase();
                triggers.push(nameRu[0]);
                if (nameRu.length >= 2) triggers.push(nameRu.substring(0, 2));
            }
            triggers.push(simpleName[0]);
            triggers.push(simpleName.substring(0, 2));
            triggers = [...new Set(triggers)];

            const names = [name];
            if (city.nameRu) names.push(city.nameRu.toLowerCase());
            if (simpleName !== name) names.push(simpleName);

            const importance = (0.9 - (index * 0.0005)).toFixed(4);
            const type = city.population > 100000 ? 'city' : 'town';

            content += `  {\n`;
            content += `    names: ${JSON.stringify(names)},\n`;
            content += `    triggers: ${JSON.stringify(triggers)},\n`;
            content += `    data: {\n`;
            content += `       place_id: ${city.id},\n`;
            content += `       osm_id: ${city.id},\n`;
            content += `       osm_type: "relation",\n`;
            content += `       lat: "${city.lat}",\n`;
            content += `       lon: "${city.lon}",\n`;
            content += `       display_name: "${city.name.replace(/"/g, '\\"')}, Germany",\n`;
            content += `       class: "place",\n`;
            content += `       type: "${type}",\n`;
            content += `       importance: ${importance},\n`;
            content += `       licence: "", boundingbox: []\n`;
            content += `    }\n`;
            content += `  },\n`;
        });

        content += `];\n`;

        fs.writeFileSync('src/constants/germanCities.ts', content);
        console.log("File written to src/constants/germanCities.ts");

    } catch (e) {
        console.error("Error:", e);
    }
}

fetchMajorCities();
